language: java

services:
  - docker

before_install:
  - docker pull axoniq/axonserver:latest
  - docker run -d --name axon-server -p 8024:8024 -p 8124:8124 axoniq/axonserver:latest
  - docker pull mongo:latest
  - docker run -it -d --name mongo-container -p 27017:27017 -v mongo_data_container:/data/db mongo:latest
  - docker pull mysql:latest
  - docker run -it -d --name mysql-container -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -v mysql_data_container:/var/lib/mysql mysql:latest
